# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.5.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1145, 854)
        MainWindow.setMouseTracking(True)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setMouseTracking(True)
        self.centralwidget.setObjectName("centralwidget")
        self.listWidget_image_list = QtWidgets.QListWidget(self.centralwidget)
        self.listWidget_image_list.setGeometry(QtCore.QRect(480, 630, 651, 171))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.listWidget_image_list.setFont(font)
        self.listWidget_image_list.setObjectName("listWidget_image_list")
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(110, 110, 1031, 511))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout.setContentsMargins(9, 9, 9, 9)
        self.horizontalLayout.setSpacing(9)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.layoutWidget1 = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget1.setGeometry(QtCore.QRect(9, 9, 101, 627))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget1)
        self.verticalLayout.setContentsMargins(9, 9, 9, 18)
        self.verticalLayout.setSpacing(9)
        self.verticalLayout.setObjectName("verticalLayout")
        self.pushButton_Head = QtWidgets.QPushButton(self.layoutWidget1)
        self.pushButton_Head.setMinimumSize(QtCore.QSize(0, 78))
        self.pushButton_Head.setMaximumSize(QtCore.QSize(78, 16777215))
        self.pushButton_Head.setCheckable(True)
        self.pushButton_Head.setObjectName("pushButton_Head")
        self.verticalLayout.addWidget(self.pushButton_Head)
        self.pushButton_LShouder = QtWidgets.QPushButton(self.layoutWidget1)
        self.pushButton_LShouder.setMinimumSize(QtCore.QSize(0, 78))
        self.pushButton_LShouder.setMaximumSize(QtCore.QSize(78, 16777215))
        self.pushButton_LShouder.setMouseTracking(True)
        self.pushButton_LShouder.setCheckable(True)
        self.pushButton_LShouder.setObjectName("pushButton_LShouder")
        self.verticalLayout.addWidget(self.pushButton_LShouder)
        self.pushButton_LAncon = QtWidgets.QPushButton(self.layoutWidget1)
        self.pushButton_LAncon.setMinimumSize(QtCore.QSize(0, 78))
        self.pushButton_LAncon.setMaximumSize(QtCore.QSize(78, 16777215))
        self.pushButton_LAncon.setCheckable(True)
        self.pushButton_LAncon.setObjectName("pushButton_LAncon")
        self.verticalLayout.addWidget(self.pushButton_LAncon)
        self.pushButton_LHand = QtWidgets.QPushButton(self.layoutWidget1)
        self.pushButton_LHand.setMinimumSize(QtCore.QSize(0, 78))
        self.pushButton_LHand.setMaximumSize(QtCore.QSize(78, 16777215))
        self.pushButton_LHand.setCheckable(True)
        self.pushButton_LHand.setObjectName("pushButton_LHand")
        self.verticalLayout.addWidget(self.pushButton_LHand)
        self.pushButton_RShouder = QtWidgets.QPushButton(self.layoutWidget1)
        self.pushButton_RShouder.setMinimumSize(QtCore.QSize(0, 78))
        self.pushButton_RShouder.setMaximumSize(QtCore.QSize(78, 16777215))
        self.pushButton_RShouder.setCheckable(True)
        self.pushButton_RShouder.setObjectName("pushButton_RShouder")
        self.verticalLayout.addWidget(self.pushButton_RShouder)
        self.pushButton_RAncon = QtWidgets.QPushButton(self.layoutWidget1)
        self.pushButton_RAncon.setMinimumSize(QtCore.QSize(0, 78))
        self.pushButton_RAncon.setMaximumSize(QtCore.QSize(78, 16777215))
        self.pushButton_RAncon.setCheckable(True)
        self.pushButton_RAncon.setObjectName("pushButton_RAncon")
        self.verticalLayout.addWidget(self.pushButton_RAncon)
        self.pushButton_RHand = QtWidgets.QPushButton(self.layoutWidget1)
        self.pushButton_RHand.setMinimumSize(QtCore.QSize(0, 78))
        self.pushButton_RHand.setMaximumSize(QtCore.QSize(78, 16777215))
        self.pushButton_RHand.setCheckable(True)
        self.pushButton_RHand.setObjectName("pushButton_RHand")
        self.verticalLayout.addWidget(self.pushButton_RHand)
        self.layoutWidget2 = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget2.setGeometry(QtCore.QRect(120, 10, 481, 98))
        self.layoutWidget2.setObjectName("layoutWidget2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.layoutWidget2)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.lineEdit_dirSaveImage = QtWidgets.QLineEdit(self.layoutWidget2)
        self.lineEdit_dirSaveImage.setReadOnly(True)
        self.lineEdit_dirSaveImage.setObjectName("lineEdit_dirSaveImage")
        self.horizontalLayout_3.addWidget(self.lineEdit_dirSaveImage)
        self.pushButton_dirSaveImage = QtWidgets.QPushButton(self.layoutWidget2)
        self.pushButton_dirSaveImage.setObjectName("pushButton_dirSaveImage")
        self.horizontalLayout_3.addWidget(self.pushButton_dirSaveImage)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.lineEdit_RGBdirSaveImage = QtWidgets.QLineEdit(self.layoutWidget2)
        self.lineEdit_RGBdirSaveImage.setReadOnly(True)
        self.lineEdit_RGBdirSaveImage.setObjectName("lineEdit_RGBdirSaveImage")
        self.horizontalLayout_8.addWidget(self.lineEdit_RGBdirSaveImage)
        self.pushButton_RGBdirSaveImage = QtWidgets.QPushButton(self.layoutWidget2)
        self.pushButton_RGBdirSaveImage.setObjectName("pushButton_RGBdirSaveImage")
        self.horizontalLayout_8.addWidget(self.pushButton_RGBdirSaveImage)
        self.verticalLayout_2.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.lineEdit_dirSaveAnnotation = QtWidgets.QLineEdit(self.layoutWidget2)
        self.lineEdit_dirSaveAnnotation.setReadOnly(True)
        self.lineEdit_dirSaveAnnotation.setObjectName("lineEdit_dirSaveAnnotation")
        self.horizontalLayout_4.addWidget(self.lineEdit_dirSaveAnnotation)
        self.pushButton_dirSaveAnnotation = QtWidgets.QPushButton(self.layoutWidget2)
        self.pushButton_dirSaveAnnotation.setObjectName("pushButton_dirSaveAnnotation")
        self.horizontalLayout_4.addWidget(self.pushButton_dirSaveAnnotation)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
        self.pushButton_delete_files = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_delete_files.setGeometry(QtCore.QRect(20, 650, 80, 71))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_delete_files.sizePolicy().hasHeightForWidth())
        self.pushButton_delete_files.setSizePolicy(sizePolicy)
        self.pushButton_delete_files.setMinimumSize(QtCore.QSize(0, 68))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 170, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 170, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(190, 190, 190))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 170, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        self.pushButton_delete_files.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("STIXVariants")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_delete_files.setFont(font)
        self.pushButton_delete_files.setObjectName("pushButton_delete_files")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setEnabled(True)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1145, 23))
        self.menubar.setObjectName("menubar")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        self.menu_2 = QtWidgets.QMenu(self.menubar)
        self.menu_2.setObjectName("menu_2")
        self.menu_3 = QtWidgets.QMenu(self.menubar)
        self.menu_3.setObjectName("menu_3")
        MainWindow.setMenuBar(self.menubar)
        self.action_openImageFolder = QtWidgets.QAction(MainWindow)
        self.action_openImageFolder.setObjectName("action_openImageFolder")
        self.action_openRGBVideo = QtWidgets.QAction(MainWindow)
        self.action_openRGBVideo.setObjectName("action_openRGBVideo")
        self.action_openDepthVideo = QtWidgets.QAction(MainWindow)
        self.action_openDepthVideo.setObjectName("action_openDepthVideo")
        self.action_5 = QtWidgets.QAction(MainWindow)
        self.action_5.setObjectName("action_5")
        self.action_6 = QtWidgets.QAction(MainWindow)
        self.action_6.setObjectName("action_6")
        self.action_last_page = QtWidgets.QAction(MainWindow)
        self.action_last_page.setObjectName("action_last_page")
        self.action_next_page = QtWidgets.QAction(MainWindow)
        self.action_next_page.setObjectName("action_next_page")
        self.action = QtWidgets.QAction(MainWindow)
        self.action.setObjectName("action")
        self.action_2 = QtWidgets.QAction(MainWindow)
        self.action_2.setObjectName("action_2")
        self.action_3 = QtWidgets.QAction(MainWindow)
        self.action_3.setObjectName("action_3")
        self.menu.addAction(self.action_openImageFolder)
        self.menu.addAction(self.action_openRGBVideo)
        self.menu.addAction(self.action_openDepthVideo)
        self.menu.addSeparator()
        self.menu.addAction(self.action)
        self.menu.addAction(self.action_3)
        self.menu_2.addAction(self.action_5)
        self.menu_2.addAction(self.action_6)
        self.menu_3.addAction(self.action_last_page)
        self.menu_3.addAction(self.action_next_page)
        self.menu_3.addAction(self.action_2)
        self.menubar.addAction(self.menu.menuAction())
        self.menubar.addAction(self.menu_2.menuAction())
        self.menubar.addAction(self.menu_3.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton_Head.setText(_translate("MainWindow", "头"))
        self.pushButton_Head.setShortcut(_translate("MainWindow", "W"))
        self.pushButton_LShouder.setText(_translate("MainWindow", "左肩"))
        self.pushButton_LShouder.setShortcut(_translate("MainWindow", "Q"))
        self.pushButton_LAncon.setText(_translate("MainWindow", "左肘"))
        self.pushButton_LAncon.setShortcut(_translate("MainWindow", "A"))
        self.pushButton_LHand.setText(_translate("MainWindow", "左手"))
        self.pushButton_LHand.setShortcut(_translate("MainWindow", "Z"))
        self.pushButton_RShouder.setText(_translate("MainWindow", "右肩"))
        self.pushButton_RShouder.setShortcut(_translate("MainWindow", "E"))
        self.pushButton_RAncon.setText(_translate("MainWindow", "右肘"))
        self.pushButton_RAncon.setShortcut(_translate("MainWindow", "D"))
        self.pushButton_RHand.setText(_translate("MainWindow", "右手"))
        self.pushButton_RHand.setShortcut(_translate("MainWindow", "C"))
        self.pushButton_dirSaveImage.setText(_translate("MainWindow", "深度图像路径"))
        self.pushButton_RGBdirSaveImage.setText(_translate("MainWindow", "彩色图像路径"))
        self.pushButton_dirSaveAnnotation.setText(_translate("MainWindow", "保存标注路径"))
        self.pushButton_delete_files.setText(_translate("MainWindow", "删 除\n"
"文 件"))
        self.pushButton_delete_files.setShortcut(_translate("MainWindow", "Ctrl+D"))
        self.menu.setTitle(_translate("MainWindow", "文件"))
        self.menu_2.setTitle(_translate("MainWindow", "标注类型"))
        self.menu_3.setTitle(_translate("MainWindow", "操作"))
        self.action_openImageFolder.setText(_translate("MainWindow", "打开图像文件夹"))
        self.action_openRGBVideo.setText(_translate("MainWindow", "打开彩色视频文件"))
        self.action_openDepthVideo.setText(_translate("MainWindow", "打开深度视频文件"))
        self.action_5.setText(_translate("MainWindow", "点类型"))
        self.action_6.setText(_translate("MainWindow", "矩形类型"))
        self.action_last_page.setText(_translate("MainWindow", "上一张"))
        self.action_last_page.setShortcut(_translate("MainWindow", "1"))
        self.action_next_page.setText(_translate("MainWindow", "下一张"))
        self.action_next_page.setShortcut(_translate("MainWindow", "3"))
        self.action.setText(_translate("MainWindow", "设置图像保存路径"))
        self.action_2.setText(_translate("MainWindow", "保存图像以及标注信息"))
        self.action_3.setText(_translate("MainWindow", "设置标注文件保存信息"))

